[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"

# Branch Deploy context: all deploys that are not from
# a pull/merge request or from the Production branch 
# will inherit these settings.
[context.branch-deploy.environment]
  NODE_ENV = "development"

# assets processing config
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = true
[build.processing.js]
  bundle = false
  minify = true
[build.processing.html]
  pretty_urls = false
[build.processing.images]
  compress = true

# force redirect to our domain if someone is still using the netlify domain
[[redirects]]
 from = "https://builders-doc.netlify.app"
 to = "https://asean.buildtheearth.asia"
 status = 301
 force = true
[[redirects]]
 from = "https://builders-doc.netlify.app/*"
 to = "https://asean.buildtheearth.asia/:splat"
 status = 301
 force = true

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
      # only allow using iframe in origin site
      X-Frame-Options = "SAMEORIGIN"
      # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection
      X-XSS-Protection = "1; mode=block"

# /assets folder contain Webpack processed assets with a file hash
# They are safe for immutable caching, as filename change when content change
[[headers]]
  for = "/assets/*"
    [headers.values]
      Cache-Control = '''
        public,
        max-age=365000000,
        immutable'''
[[headers]]
  for = "/id/assets/*"
    [headers.values]
      Cache-Control = '''
        public,
        max-age=365000000,
        immutable'''
[[headers]]
  for = "/my/assets/*"
    [headers.values]
      Cache-Control = '''
        public,
        max-age=365000000,
        immutable'''
[[headers]]
  for = "/ph/assets/*"
    [headers.values]
      Cache-Control = '''
        public,
        max-age=365000000,
        immutable'''
[[headers]]
  for = "/th/assets/*"
    [headers.values]
      Cache-Control = '''
        public,
        max-age=365000000,
        immutable'''
[[headers]]
  for = "/vn/assets/*"
    [headers.values]
      Cache-Control = '''
        public,
        max-age=365000000,
        immutable'''
